version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: hadestran/node-app
    # ports:
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
      - nginx

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    # container_name: my-redis
    # ports:
    #   - '6379:6379'

volumes:
  mongo-db:
