version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 4
        deplay: 10s
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_NAME=admin
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
